name: Website Monitor

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  run-monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run monitor script
        id: monitor_result
        run: |
          python monitor.py

      - name: 发送微信通知
        if: steps.monitor_result.outputs.changed == 'true'
        run: |
          curl "https://sctapi.ftqq.com/${{ secrets.SENDKEY }}.send?title=监控网站更新提醒&desp=百度新闻页面发生了变化，请查看！"

      - name: Commit & push log
        run: |
          git config --global user.name "github‑actions[bot]"
          git config --global user.email "github‑actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "auto update log" || echo "no changes"
          git push
